name: 03 runners OS check
on: workflow_dispatch
jobs:
    ubuntu-os:
        runs-on: ubuntu-latest
        steps:
            - name: check the OS
              run: |
                echo "This job is running on an Ubuntu runner."
                echo "The runners OS is: $RUNNER_OS"
    windows-os:
        runs-on: windows-latest
        steps:
            - name: check the os
              shell: bash
              run: |
                echo "This job is running on a Windows runner."
                echo "The runners OS is: $RUNNER_OS"
