name: 05 event filters 
on:
    pull_request: 
      types: [ opened, synchronize, reopened, closed ]
      branches:
        - main
      branches-ignore:      
        - develop
        - feature/**
jobs:
    event-filter-check:
        runs-on: ubuntu-latest
        steps:
            - name: check event action
              run: |
                echo "I have been triggered by a pull_request event with the action: ${{ github.event.action }}."