name: 07 expressions
run-name: Check expressions based on input | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
on:
    workflow_dispatch:
        inputs:
            debug:
                description: " this is for defind the debug level"
                type: boolean
                required: true
                default: false
jobs:
    check-expressions:
        runs-on: ubuntu-latest
        steps:
            - name: Check expressions
              if: inputs.debug
              run: |
                echo "Debug mode is enabled."
                echo "The debug input value is: ${{ inputs.debug }}"

            - name: '[debug] Print when triggered from main'
              if: inputs.debug || github.ref == 'refs/heads/main'
              run: echo "I was triggered from main"