name: 08 vars
on: 
    push:
    workflow_dispatch:
env:
    UNDEFINED_VAR: "${{ vars.UNDEFINED_VAR }} || 'default value' }}"
jobs:
    echo-vars:
        runs-on: ubuntu-latest
        steps:
            - name: print the repo vars
              run: |
                echo "The repo var is: ${{ vars.REPO_VAR }}"
                echo "The repo var2 is: $REPO_VAR2"
                echo "undefined var is : ${{ env.UNDEFINED_VAR }}"