name: 09-functions 
on:
    push:
    workflow_dispatch:
jobs:
    use-functions:
        runs-on: ubuntu-latest
        steps:
            - name: fail the task
              run: | 
                echo "This step will fail."
                exit 1
            - name: success message
              if: ${{ success() }}
              run: echo "The previous step succeeded!"
            - name: failure message
              if: ${{ failure() }}
              run: echo "The previous step failed!"
            - name: always message
              if: ${{ always() }}
              run: echo "This message runs regardless of the previous step's outcome."
            - name: cancelled message
              if: ${{ cancelled() }}
              run: echo "The workflow was cancelled."