name: 12 outputs example workflow
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
            output2: ${{ steps.build.outputs.output2 }}
        steps:
            - name: build
              id: build
              run: |
                echo "status=success" >> $GITHUB_OUTPUT
                echo "output1=value1" >> $GITHUB_OUTPUT
                echo "output2=value2" >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: deploying the application
              run: |
                echo "Deploying with output1: ${{ needs.build.outputs.output1 }} and output2: ${{ needs.build.outputs.output2 }}"