name: 12 outputs example workflow
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                description: 'Expected build status to proceed with deployment'
                required: true
                options:
                    - 'success'
                    - 'failure'
                default: 'success'
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ inputs.build-status }}
            output1: ${{ steps.build.outputs.output1 }}
            output2: ${{ steps.build.outputs.output2 }}
        steps:
            - name: build
              id: build
              run: |
                echo "status=success" >> $GITHUB_OUTPUT
                echo "output1=value1" >> $GITHUB_OUTPUT
                echo "output2=value2" >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: deploying the application
              run: |
                echo "Deploying with output1: ${{ needs.build.outputs.output1 }} and output2: ${{ needs.build.outputs.output2 }}"